_extends: .github
name-template: $RESOLVED_VERSION
tag-template: s3-$RESOLVED_VERSION

version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking'
  minor:
    labels:
      - 'minor'
      - 'dependencies'
  patch:
    labels:
      - 'bugfix'
      - 'patch'
  default: minor